// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC2U0H2lLHNkqJvYEjHzFebNzxC5RFBl8',
    appId: '1:491172444984:web:96095da2037d4fa5309fcd',
    messagingSenderId: '491172444984',
    projectId: 'flutter-insta-8d8cc',
    authDomain: 'flutter-insta-8d8cc.firebaseapp.com',
    storageBucket: 'flutter-insta-8d8cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSIU94gF55mbIN9IUECJCHIv2TDvzdss',
    appId: '1:491172444984:android:6f0bc7692cce3b8a309fcd',
    messagingSenderId: '491172444984',
    projectId: 'flutter-insta-8d8cc',
    storageBucket: 'flutter-insta-8d8cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY8BjiIHI9enUcHVfsniOWTBJxkYdoHoU',
    appId: '1:491172444984:ios:a944174ed1d9beed309fcd',
    messagingSenderId: '491172444984',
    projectId: 'flutter-insta-8d8cc',
    storageBucket: 'flutter-insta-8d8cc.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY8BjiIHI9enUcHVfsniOWTBJxkYdoHoU',
    appId: '1:491172444984:ios:221933d792a90cfb309fcd',
    messagingSenderId: '491172444984',
    projectId: 'flutter-insta-8d8cc',
    storageBucket: 'flutter-insta-8d8cc.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
