name: blog_posts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  animations: ^2.0.11
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  word_generator: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Edu VIC WA NT Beginner
      fonts:
        - asset: assests\Edu_VIC_WA_NT_Beginner\static\EduVICWANTBeginner-Regular.ttf
        - asset: assests\Edu_VIC_WA_NT_Beginner\static\EduVICWANTBeginner-Bold.ttf
